### ISSUE TITLE
[DISCUSSION] Class selection

### ISSUE THREAD

**Issue by rootatkali** [kfaryarok/kfaryarok-android#19]
I think that the class selection should be a dropdown menu instead of a textbox, just so there'll be compatibility between what the user types and what the app parses.

**Comment by Tbsc** [comment]
I wanted it to be like that too, but Android's Preferences API is really lacking doesn't let me do that easily. I made it a textbox because I just needed something to work for testing the app. I'll do it, but first there are some important bugs with alerts that I need to fix (going off at random times is a big one!)

**Comment by Tbsc** [comment]
There are two ways to do this:
1. One list with every possible class, and let the user choose from there
2. Two lists, and you match a grade with a class number
Both of them are roughly the same difficulty, so it's more of a design problem. The second option is much more practical for both users and me (as a developer), so I'm leaning towards that.

There's still another problem, how will the user select the grade/class:
a. One button for both, that shows a dialog for selecting both (probably two lists, side by side)
b. Two buttons, that each one of them is responsible for grade/class
Option B will be much easier to develop, but I think it will also be much uglier. I'm willing to do option A even though it's harder because I really think it would look much better, but I want your opinion.

**Comment by rootatkali** [comment]
Like you, I'm leaning towards option A.

**Comment by Tbsc** [comment]
After almost 2 weeks, I finally got it (option A) working. See pull request #21.
